/*

 BACKGROUNDTILEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : tileset1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 38
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __BackgroundTileMap_h_INCLUDE
#define __BackgroundTileMap_h_INCLUDE

#define BackgroundTileMapWidth 32
#define BackgroundTileMapHeight 18
#define BackgroundTileMapNumberSpawnPositions 71
#define BackgroundTileMapBank 0

extern const unsigned char BackgroundTileMap[];
extern const int BackgroundTileMapSpawnPositions[];

#endif

/* End of BACKGROUNDTILEMAP.H */
